TestNPCGuy:
  Sex: Male
  Health: 200
  Helmet Prefab Name: HelmetYule
  Chest Armor Prefab Name: ArmorFenringChest
  Legs Armor Prefab Name: ArmorFenringLegs
  Shoulder Armor Prefab Name: CapeTrollHide
  Weapon Prefab Name: FistFenrirClaw
  Shield Prefab Name: ShieldBoneTower
  Faction: Players
  HuntPlayer: true
  Scale: 1.0
  Tamable: false
  Hair Style: Hair2
  Skin Color R: 102
  Skin Color G: 0
  Skin Color B: 10
  Hair Color R: 12
  Hair Color G: 100
  Hair Color B: 200
  Tolerate Water: true
  Tolerate Fire: true
  Tolerate Smoke: true
  Tolerate Tar: false
  Damage Resists:
    Blunt: Very
    Slash: None
    Pierce: Ignore
    Chop: Resistant
    Pickaxe: Very Resistant
    Fire: Immune
    Frost: Normal
    Lightning: Normal
    Poison: Normal
    Spirit: Immune
  Monster AI Config:
    View Range: 20
    View Angle: 90
    Hear Range: 9999
    Alert Range: 100
    Flee if hurt cant be reached: false
    Flee if not alerted: false
    Flee low health: 0
    Circulate while Charging: true
    Attack player objects: true
    Intercept Time Max: 20
    Intercept Time Min: 5
    Chase Distance: 25
    Attack Interval: 5
    Circualate Target Duration: 3
    Circle Target Distance: 5
    Hunt Player: true
  
TestNPCGirl:
  Sex: Female
  Health: 200
  Helmet Prefab Name: HelmetYule
  Chest Armor Prefab Name: ArmorFenringChest
  Legs Armor Prefab Name: ArmorFenringLegs
  Shoulder Armor Prefab Name: CapeTrollHide
  Weapon Prefab Name: FistFenrirClaw
  Shield Prefab Name: ShieldBoneTower
  Faction: Players
  HuntPlayer: true
  Scale: 1.0
  Tamable: false
  Hair Style: Hair1
  Skin Color R: 102
  Skin Color G: 0
  Skin Color B: 10
  Hair Color R: 255
  Hair Color G: 102
  Hair Color B: 190
  Tolerate Water: true
  Tolerate Fire: true
  Tolerate Smoke: true
  Tolerate Tar: false
  Damage Resists:
    Blunt: Very
    Slash: None
    Pierce: Ignore
    Chop: Resistant
    Pickaxe: Very Resistant
    Fire: Immune
    Frost: Normal
    Lightning: Normal
    Poison: Normal
    Spirit: Immune
  Monster AI Config:
    View Range: 20
    View Angle: 90
    Hear Range: 9999
    Alert Range: 100
    Flee if hurt cant be reached: false
    Flee if not alerted: false
    Flee low health: 0
    Circulate while Charging: true
    Attack player objects: true
    Intercept Time Max: 20
    Intercept Time Min: 5
    Chase Distance: 25
    Attack Interval: 5
    Circualate Target Duration: 3
    Circle Target Distance: 5
    Hunt Player: true