Frank:
  Sex: Male
  Health: 200
  Set Configurations:
    1:
      Helmet Prefab Names: [ "HelmetYule" ]
      Chest Armor Prefab Names: [ "ArmorFenringChest", "ArmorIronChest" ]
      Legs Armor Prefab Names: [ "ArmorFenringLegs", "ArmorLeatherLegs" ]
      Shoulder Armor Prefab Names: [ "CapeTrollHide", "CapeLox" ]
  Weapon Prefab Name: ["FistFenrirClaw", "BattleaxeCrystal","GoblinSword"]
  Shield Prefab Name: ["ShieldBoneTower", "ShieldBlackmetal"]
  Faction: Player
  Scale: 1.0
  Tamable: false
  Hair Style: ["Hair2", "Hair4", "Hair1"]
  Skin Color R: 0.847
  Skin Color G: 0.687
  Skin Color B: 0.494
  Hair Color R: 1
  Hair Color G: 0.881
  Hair Color B: 0.697
  Tolerate Water: true
  Tolerate Fire: true
  Tolerate Smoke: true
  Tolerate Tar: true
  NPC In Game Name: Frank
  #Only one can be true, please choose accordingly
  Is Basic Villager: false
  Villager Builder: false
  Villager Farmer: false
  Villager Messenger: false
  Villager RaidMaster: true
  Villager SkillMaster: false
  SkillMaster Skills:
    Skill Names: ["Swords"]
    Item Names: ["Wood", "Stone"]
  Damage Resists:
    Blunt: Very
    Slash: None
    Pierce: Ignore
    Chop: Resistant
    Pickaxe: Very Resistant
    Fire: Immune
    Frost: Normal
    Lightning: Normal
    Poison: Normal
    Spirit: Immune
  Monster AI Config:
    View Range: 30
    View Angle: 90
    Hear Range: 9999
    Alert Range: 1000
    Flee if hurt cant be reached: false
    Flee if not alerted: false
    Flee low health: 0
    Circulate while Charging: true
    Attack player objects: true
    Intercept Time Max: 5
    Intercept Time Min: 1
    Chase Distance: 25
    Attack Interval: 0
    Circulate Target Duration: 3
    Circle Target Distance: 5
    Hunt Player: true
    Avoid Water: false
    Avoid Land: false
    Avoid Fire: false
    Random Move Interval: 5.0
    Random Move Range: 10.0
  DropTable:
    Wood:
      Drop Chance: 1
      One Per Player: false
      Amount Max Chance: 4
      Amount Min Chance: 1
      Multiply for multiple Players: false
Jim:
  Sex: Male
  Health: 200
  Set Configurations:
    1:
      Helmet Prefab Names: [ "HelmetYule" ]
      Chest Armor Prefab Names: [ "ArmorFenringChest", "ArmorIronChest" ]
      Legs Armor Prefab Names: [ "ArmorFenringLegs", "ArmorLeatherLegs" ]
      Shoulder Armor Prefab Names: [ "CapeTrollHide", "CapeLox" ]
  Weapon Prefab Name: ["FistFenrirClaw", "BattleaxeCrystal","GoblinSword"]
  Shield Prefab Name: ["ShieldBoneTower", "ShieldBlackmetal"]
  Faction: Player
  Scale: 1.0
  Tamable: true
  Hair Style: ["Hair2", "Hair4", "Hair1"]
  Skin Color R: 0.847
  Skin Color G: 0.687
  Skin Color B: 0.494
  Hair Color R: 1
  Hair Color G: 0.881
  Hair Color B: 0.697
  Tolerate Water: true
  Tolerate Fire: true
  Tolerate Smoke: true
  Tolerate Tar: true
  NPC In Game Name: Frank
  #Only one can be true, please choose accordingly
  Is Basic Villager: true
  Villager Builder: false
  Villager Farmer: false
  Villager Messenger: false
  Villager RaidMaster: false
  Villager SkillMaster: false
  SkillMaster Skills:
    Skill Names: ["Swords"]
    Item Names: ["Wood", "Stone"]
  Damage Resists:
    Blunt: Very
    Slash: None
    Pierce: Ignore
    Chop: Resistant
    Pickaxe: Very Resistant
    Fire: Immune
    Frost: Normal
    Lightning: Normal
    Poison: Normal
    Spirit: Immune
  Monster AI Config:
    View Range: 30
    View Angle: 90
    Hear Range: 9999
    Alert Range: 1000
    Flee if hurt cant be reached: false
    Flee if not alerted: false
    Flee low health: 0
    Circulate while Charging: true
    Attack player objects: true
    Intercept Time Max: 5
    Intercept Time Min: 1
    Chase Distance: 25
    Attack Interval: 0
    Circulate Target Duration: 3
    Circle Target Distance: 5
    Hunt Player: true
    Avoid Water: false
    Avoid Land: false
    Avoid Fire: false
    Random Move Interval: 5.0
    Random Move Range: 10.0
  DropTable:
    Wood:
      Drop Chance: 1
      One Per Player: false
      Amount Max Chance: 4
      Amount Min Chance: 1
      Multiply for multiple Players: false
    Stone:
      Drop Chance: 1
      One Per Player: false
      Amount Max Chance: 1
      Amount Min Chance: 1
      Multiply for multiple Players: false